version: "3.9"
services:
  postgresql:
    image: postgres:16.2-alpine3.19
    container_name: "f1-app-postgresql"
    env_file:
      - .env.local
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
    volumes:
      - ./packages/server/f1-csv:/csv
    ports:
      - "5432:5432"