name: npm-client
run-name: ${{ github.actor }} installing client dependencies
on:
#  push:
#    branches:
#      - master
#      - develop
#  pull_request:
#    branches:
#      - master
#      - develop
  [push, pull_request]
jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: docker-build-client
        run: docker build -f ../../packages/client/Dockerfile -t f1-app/client --target ci --label f1-app/client ../../
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: cd ./packages/client
      - id: client-unit-tests
        run: npm run test
      - id: client-e2e-tests
        run: npm run test:e2e